---
- name: Install and configure Nginx
  hosts: all
  become: yes  # Use 'sudo' to execute commands with superuser privileges
  tasks:
    - name: Update the package index
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Nginx
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Ensure Nginx is listening on port 80
      wait_for:
        port: 80
        delay: 10
        timeout: 60
